[package]
publish = false
name = "trading-assistant"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
crb.workspace = true
env_logger.workspace = true
ice-nine-core.path = "../../essential/core"
ice-nine-plugin-exchange-dydx.path = "../../plugins/exchange-dydx"
ice-nine-plugin-messaging-telegram.path = "../../plugins/messaging-telegram"
ice-nine-plugin-model-openai.path = "../../plugins/model-openai"
tokio.workspace = true
