[workspace]
resolver = "2"
members = [
    "essential/*",
    "examples/*",
    "plugins/*",
    "tools/*",
]
exclude = [
    # "examples",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "?"

[workspace.dependencies]
anyhow = "1.0.95"
async-trait = "0.1.85"
crb.git = "https://github.com/runtime-blocks/crb"
derive_more = "1.0.0"
dotenvy = "0.15.7"
env_logger = "0.11.6"
envy = "0.4.2"
futures = "0.3.31"
ice-nine-core.path = "essential/core"
log = "0.4.22"
serde = "1.0.217"
tokio = "1.42.0"
