[package]
name = "ice-nine-std"
description = "Integration with the standard OS environment: files, sockets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
