[package]
name = "ui9-tool-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
crb.workspace = true
crossterm = "0.28.1"
ratatui = "0.29.0"
tokio.workspace = true
