[package]
name = "n9"
description = "Nine - Nethermind Intelligent Node Environment - AI agents framework"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
crb.workspace = true
