[package]
name = "ice9"
description = "AI agents runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ice9-core.workspace = true
